

export const GET_BUSINESS_LOAD = "GET_BUSINESS_LOAD";
export const GET_BUSINESS_SUCCESS = "GET_BUSINESS_SUCCESS";
export const GET_BUSINESS_FAIL = "GET_BUSINESS_FAIL";

export const GET_ONE_BUSINESS_LOAD = "GET_ONE_BUSINESS_LOAD";
export const GET_ONE_BUSINESS_SUCCESS = "GET_ONE_BUSINESS_SUCCESS";
export const GET_ONE_BUSINESS_FAIL = "GET_ONE_BUSINESS_FAIL";

export const ADD_BUSINESS_LOAD = "ADD_BUSINESS_LOAD";
export const ADD_BUSINESS_SUCCESS = "ADD_BUSINESS_SUCCESS";
export const ADD_BUSINESS_FAIL = "ADD_BUSINESS_FAIL";

export const DELETE_BUSINESS_LOAD = "DELETE_BUSINESS_LOAD";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_FAIL = "DELETE_BUSINESS_FAIL";

export const UPDATE_BUSINESS_LOAD = "UPDATE_BUSINESS_LOAD";
export const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
export const UPDATE_BUSINESS_FAIL = "UPDATE_BUSINESS_FAIL";

export const CLEAR_ERRORS_BUSINESS = "CLEAR_ERRORS_BUSINESS";
export const CLEAR_SUCCESS_BUSINESS = "CLEAR_SUCCESS_BUSINESS";


